### ISSUE TITLE
JSON error passing numpy arrays over pysmurf controller

### ISSUE THREAD

**Issue by csierra2** [simonsobs/socs#380]
This is happening when I pass a numpy array as a kwarg to pysmurf-controller's `take_iv`, e.g.

```
pysmurf_uv31 = matched_client.OCSClient('pysmurf-controller-s4', args=[])
bgs = np.arange(12)
pysmurf_uv31.take_iv.start(kwargs =  {'bias_groups': bgs, 'overbias_wait': 1, 'bias_high': 20})
print( pysmurf_uv31.take_iv.wait() )
```

leads to this error:
```
Traceback (most recent call last):
  File "test_pysmurf_iv.py", line 24, in <module>
    pysmurf_uv31.take_iv.start(kwargs = iv_args)
  File "/home/mcmlab/.local/lib/python3.8/site-packages/ocs/ocs_client.py", line 23, in start
    return OCSReply(*client.request('start', name, params=kwargs))
  File "/home/mcmlab/.local/lib/python3.8/site-packages/ocs/client_http.py", line 99, in request
    return self.call(self.agent_addr + '.ops', action, op_name, params, **kw)
  File "/home/mcmlab/.local/lib/python3.8/site-packages/ocs/client_http.py", line 26, in call
    params = json.dumps({'procedure': procedure,
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```
The script works if I pass it a list instead.

**Comment by BrianJKoopman** [comment]
Thanks for the bug report @csierra2! This is because data passed over the crossbar server is serialized. `numpy` arrays are not serializable, as the error says. I take it `bgs` is the numpy array in your example?

This will need to be fixed in ocs core. Likely we could detect numpy arrays and convert them to a list before making the request from the client. Otherwise we could catch this and display an informative message. I might move this issue over to that repo. Until we can fix, you'll have to pass lists instead.
