### ISSUE TITLE
Wiregrid Actuator glibc library installation issues

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/socs#754]
The wiregrid actuator is one of the unique [agent images](https://github.com/simonsobs/socs/blob/main/docker/wiregrid_actuator/Dockerfile) that gets built here. It requires glibc. Recent images (`v0.5.1-22-g7d2f158-dev`) are failing to run, with the following error:
```
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
    self._handle = _dlopen(self._name, mode)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
  File "/opt/venv/lib/python3.10/site-packages/gclib-1.0-py3.10.egg/gclib.py", line 61, in <module>
    import gclib
  File "/opt/venv/lib/python3.10/site-packages/socs/agents/wiregrid_actuator/drivers/Actuator.py", line 8, in <module>
    from socs.agents.wiregrid_actuator.drivers.Actuator import Actuator
  File "/opt/venv/lib/python3.10/site-packages/socs/agents/wiregrid_actuator/agent.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    mod = importlib.import_module(_module)
  File "/opt/venv/lib/python3.10/site-packages/ocs/agent_cli.py", line 201, in main
    sys.exit(main())
  File "/opt/venv/bin/ocs-agent-cli", line 8, in <module>
Traceback (most recent call last):
Installed OCS Plugins: ['socs', 'ocs']
Args: ['--instance-id', 'wg-actuator', '--site-hub', 'ws://127.0.0.1:8005/ws', '--site-http', 'http://127.0.0.1:8005/call']
/usr/sbin/gcapsd: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
   ...done.
Process 23 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)
 * Starting Avahi mDNS/DNS-SD Daemon avahi-daemon
   ...done.
 * Starting system message bus dbus

 * Removing stale PID file /var/run/dbus/pid.
```

This needs some triage, but I expect this started happening due to https://github.com/simonsobs/socs/pull/714. This updated the Python version from 3.8 to 3.10 within the image.

Also noted that the links to documentation for installation of glibc from the [socs docs](https://socs.readthedocs.io/en/main/agents/wiregrid_actuator.html) are dead. New docs can be found here: https://www.galil.com/sw/pub/all/doc/global/install/linux/ubuntu/

The installation procedure has changed a bit. Probably worth just trying to update the installation process in the Dockerfile and testing the resulting image.

**Comment by BrianJKoopman** [comment]
This was resolved by #759.
